export interface ActionGenericResponse {
    userAccountObjectId: string,
    state: string,
    numberOfItems: number,
    method: BatchProcessMethod,
    startDate: Date,
    endDate: Date,
    batchLogHeaderId: number,
}

export interface BatchProcessUserLockDbVO {
    userAccountObjectId: string,
    lockDate: Date,
}

export interface BatchProcessLogHeaderDbVO {
        userAccountObjectId: string,
        state: BatchProcessLogHeaderState,
        numberOfItems: number,
        percentageOfProcessedItems: number,
        method: BatchProcessMethod,
        startDate: Date,
        endDate: Date,
        batchLogHeaderId: number
}

export interface BatchProcessLogDetailDbVO {
    batchProcessLogDetailId: number,
    batchProcessLogHeaderDbVO: BatchProcessLogHeaderDbVO,
    itemObjectId: string,
    itemVersionnumber: number,
    state: BatchProcessLogDetailState,
    message: BatchProcessMessages,
    startDate: Date,
    endDate: Date,
    batchLogDetailId: number
}

export enum BatchProcessMessages {
    BATCH_SUCCESS = "BATCH_SUCCESS",
    BATCH_AUTHENTICATION_ERROR = "BATCH_AUTHENTICATION_ERROR",
    BATCH_AUTHORIZATION_ERROR = "BATCH_AUTHORIZATION_ERROR",
    BATCH_CONTEXT_NOT_FOUND = "BATCH_CONTEXT_NOT_FOUND",
    BATCH_FILES_METADATA_OLD_VALUE_NOT_EQUAL = "BATCH_FILES_METADATA_OLD_VALUE_NOT_EQUAL",
    BATCH_INTERNAL_ERROR = "BATCH_INTERNAL_ERROR",
    BATCH_ITEM_NOT_FOUND = "BATCH_ITEM_NOT_FOUND",
    BATCH_METADATA_CHANGE_VALUE_NOT_ALLOWED = "BATCH_METADATA_CHANGE_VALUE_NOT_ALLOWED",
    BATCH_METADATA_CHANGE_VALUE_NOT_EQUAL = "BATCH_METADATA_CHANGE_VALUE_NOT_EQUAL",
    BATCH_METADATA_CHANGE_VALUE_ORCID_NO_PERSON = "BATCH_METADATA_CHANGE_VALUE_ORCID_NO_PERSON",
    BATCH_METADATA_NO_CHANGE_VALUE = "BATCH_METADATA_NO_CHANGE_VALUE",
    BATCH_METADATA_NO_NEW_VALUE_SET = "BATCH_METADATA_NO_NEW_VALUE_SET",
    BATCH_METADATA_NO_SOURCE_FOUND = "BATCH_METADATA_NO_SOURCE_FOUND",
    BATCH_STATE_WRONG = "BATCH_STATE_WRONG",
    BATCH_VALIDATION_GLOBAL = "BATCH_VALIDATION_GLOBAL",
    BATCH_VALIDATION_INVALID_ORCID = "BATCH_VALIDATION_INVALID_ORCID",
    BATCH_VALIDATION_IP_RANGE_NOT_PROVIDED = "BATCH_VALIDATION_IP_RANGE_NOT_PROVIDED",
    BATCH_VALIDATION_NO_SOURCE = "BATCH_VALIDATION_NO_SOURCE",
    BATCH_CONTEXT_NOT_OPEN = "BATCH_CONTEXT_NOT_OPEN"
}

export enum BatchProcessMessagesTypes {
    INFO = "INFO",
    ERROR = "ERROR",
    SUCCESS = "SUCCESS",
    WARNING = "WARNING",
}

export enum BatchProcessMethod {
    ADD_KEYWORDS = "ADD_KEYWORDS",
    ADD_LOCALTAGS = "ADD_LOCALTAGS",
    ADD_SOURCE_IDENTIFIER = "ADD_SOURCE_IDENTIFIER",
    CHANGE_CONTEXT = "CHANGE_CONTEXT",
    CHANGE_EXTERNAL_REFERENCE_CONTENT_CATEGORY = "CHANGE_EXTERNAL_REFERENCE_CONTENT_CATEGORY",
    CHANGE_FILE_CONTENT_CATEGORY = "CHANGE_FILE_CONTENT_CATEGORY",
    CHANGE_FILE_VISIBILITY = "CHANGE_FILE_VISIBILITY",
    CHANGE_GENRE = "CHANGE_GENRE",
    CHANGE_KEYWORDS = "CHANGE_KEYWORDS",
    CHANGE_LOCALTAG = "CHANGE_LOCALTAG",
    CHANGE_REVIEW_METHOD = "CHANGE_REVIEW_METHOD",
    CHANGE_SOURCE_GENRE = "CHANGE_SOURCE_GENRE",
    CHANGE_SOURCE_IDENTIFIER = "CHANGE_SOURCE_IDENTIFIER",
    DELETE_PUBITEMS = "DELETE_PUBITEMS",
    RELEASE_PUBITEMS = "RELEASE_PUBITEMS",
    REPLACE_FILE_AUDIENCE = "REPLACE_FILE_AUDIENCE",
    REPLACE_KEYWORDS = "REPLACE_KEYWORDS",
    REPLACE_ORCID = "REPLACE_ORCID",
    REPLACE_SOURCE_EDITION = "REPLACE_SOURCE_EDITION",
    REVISE_PUBITEMS = "REVISE_PUBITEMS",
    SUBMIT_PUBITEMS = "SUBMIT_PUBITEMS",
    WITHDRAW_PUBITEMS = "WITHDRAW_PUBITEMS",
}

export enum BatchProcessLogHeaderState {
    INITIALIZED = "INITIALIZED",
    RUNNING = "RUNNING",
    FINISHED = "FINISHED",
}

export enum BatchProcessLogDetailState {
    INITIALIZED = "INITIALIZED",
    RUNNING = "RUNNING",
    SUCCESS = "SUCCESS",
    ERROR = "ERROR",
}

