export enum Errors {
    CREATOR_FAMILY_NAME_NOT_PROVIDED,
    CREATOR_GIVEN_NAME_NOT_PROVIDED,
    CREATOR_NOT_PROVIDED,
    CREATOR_ORCID_INVALID,
    CREATOR_ORGANIZATION_NAME_NOT_PROVIDED,
    CREATOR_ROLE_NOT_PROVIDED,
    CREATOR_TYPE_NOT_PROVIDED,
    DATE_ACCEPTED_NOT_PROVIDED,
    DATE_NOT_PROVIDED,
    EVENT_TITLE_NOT_PROVIDED,
    ORGANIZATIONAL_METADATA_NOT_PROVIDED,
    

}
